Feature/update rpi imager doc
BrewBlox/brewblox-documentation pull request #248
Opened 2021-03-22 17:11 UTC by keesdaamen

Solves issue #247. Questions / discussions labeled with REVIEW.

2021-03-22 18:05 UTC, steersbob requested changes
Looks good. Some minor changes and typo fixes are required.

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +REVIEW: plaatje van het advanced menu van de RPi website. Zelf een plaatje maken kan, maar is veel werk i.v.m. scrollbar en geen 'automatic scrollbar screen capture' gevonden op linux.
Discussion notes are not content. It's best to add them as comment in the Github PR (like this).

On-topic: an image with the scrollbar active is fine. The image serves as a confirmation that the user is looking at the right menu, and we don't want it to take up too much vertical space.

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +- **Set hostname:** set a hostname to easily connect to your Pi on your network. Clear and short names work best. Default hostname is `raspberrypi`.
Missing article: **The** default hostname...

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +- **Enable SSH:** you want to enable SSH to remotely connect to your Pi through a terminal. Select *Use password authentification* and set your password.
authentification -> authentication

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +- **Configure wifi:** here you configure the network name (SSID) & password of your wifi (if applicable). Set the Wifi country setting to your country to match the wifi channels of your access point.
Can leave out "if applicable". There really is no excuse for exposing hardware controls on an unsecured wifi network.

The rest of the guide seems to somewhat consistently use the `WiFi` spelling.

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +- **Set locale settings:** set your locale settings to define the system time of your Pi and the layout of your keyboard.
Goes for the points above too: the instructions can be somewhat shortened. In this case, you can skip "set your locale settings to...", as it just repeats the information from before the colon.

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +## Step 1: Prepare the microSD card
Step 1 and 2 have become step 1. "Format" still seems the appropriate wording.

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +REVIEW: betere manier om, om te gaan met het custom hostname verhaal?
Same as before: review notes don't belong in content.

we can use `raspberrypi` in examples, if we also add a line here about users substituting the default `raspberrypi` with the hostname they chose in step 1.

2021-03-22 18:05 UTC, steersbob commented on docs/user/startup.md
> +## Step 3: Install Brewblox
I did a quick check, and there's a reference to "step 4 (Install Brewblox)" in user/system_upgrades.md

2021-03-23 14:03 UTC, keesdaamen commented on docs/user/startup.md
> +- **Configure wifi:** here you configure the network name (SSID) & password of your wifi (if applicable). Set the Wifi country setting to your country to match the wifi channels of your access point.
"if applicable" is not meant for just the password, but for using WiFi to connect to the Spark at all. I'll change it to: "Omit if you plan to use USB." Furthermore: spelling in all user guides:
- wifi 23
- Wifi 60
- WiFi 13

Of which WiFi has 2 additions by my new introductions... Which do you want to use? I intend to follow the spelling of the RPi Imager software in naming the options

2021-03-23 14:22 UTC, keesdaamen commented on docs/user/startup.md
> +## Step 3: Install Brewblox
Ok, thanks. It's fixed. I found a reference to now-non-existing Step 8 within the document as well. Searched the other User manuals too.

2021-03-23 14:36 UTC, steersbob commented on docs/user/startup.md
> +- **Configure wifi:** here you configure the network name (SSID) & password of your wifi (if applicable). Set the Wifi country setting to your country to match the wifi channels of your access point.
These wifi settings are for the Pi, not the Spark. SSH over USB is technically possible, but not a realistic option.

Googling "wifi spelling" yields that the official spelling is "Wi-Fi", but that the "Wifi", "WiFi", and "wifi" alternatives are all common enough to be acceptable.

Leave it for now, and I'll make an issue to make an official decision and refactor across all repositories.

2021-03-23 15:02 UTC, steersbob approved these changes

2021-03-23 15:02 UTC, merged